version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'
